name: Scrape CGVS Asylum Statistics

on:
  # Run monthly on the 1st day of each month at 9:00 AM UTC
  schedule:
    - cron: '0 9 1 * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to commit and push changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use token for authentication to allow pushing
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Git configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
      
      - name: Run CGVS scraper
        run: |
          chmod +x ./scrape.sh
          ./scrape.sh
          
      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update of CGVS asylum statistics - $(date +'%Y-%m-%d')"
            git push origin main
          fi
